### ISSUE TITLE
previous slide numbers don't hide and get stacked

### ISSUE THREAD

**Issue by maximousblk** [ubershmekel/redditp#100]
after sometime of using it i noticed that when the new slide numbers appear, old ones don't disappear and get stacked. can this be changed to a more conventional system like the ones below?
![Menus-fj](https://user-images.githubusercontent.com/28438021/71771517-3f171800-2f62-11ea-8d2d-f6e4aea96dcf.png)

**Comment by ubershmekel** [comment]
The current pagination definitely takes up too much space. Though I'm not sure which pagination system would be best. Maybe it makes sense to only have one row visible but still allow scrolling through the whole thing.

**Comment by maximousblk** [comment]
The last one in the image is the best. I didn't know how to implement it otherwise it would already be in the pr
