### ISSUE TITLE
Audio playing when the sound is unchecked

### ISSUE THREAD

**Issue by ubershmekel** [ubershmekel/redditp#106]
FYI @smarek this seems to be a bug with the audio checkbox. It happens when you play into a video and have the sound unchecked. To reproduce the issue on a single page on my Macbook, I find that I have to click on video, switch to a different tab, come back, click on the video, then sound plays, even though the "sound" checkbox is unticked.

https://www.redditp.com/r/youseeingthisshit/comments/fdfqwt/the_look_on_his_face_says_it_all/

https://www.reddit.com/r/redditp/comments/fc8ec2/sound_works_now_check_the_sound_checkbox/fjgr7xe/?context=3

**Comment by smarek** [comment]
Quick debug says, this issue applies to v.redd.it videos, where sound is spearate `<audio>` tag, and clicking the video somehow triggers the audio ignoring the mute settings. I'll see into this more

**Comment by ubershmekel** [comment]
Thank you @smarek 

I also added a `loop` attribute to fix the audio not looping.

https://github.com/ubershmekel/redditp/commit/378ae226ae5486576749e105d5ce1d6be6b2be87

**Comment by smarek** [comment]
well I'll be damned, thank you, totally forgot about this
