### ISSUE TITLE
redgifs not loading

### ISSUE THREAD

**Issue by matthewhale** [ubershmekel/redditp#113]
Since gyfcat banned nswf gifs from their platform, there has been a new flood of users using redgifs instead, which redditp can't handle at the moment it appears.  Just flagging this issue to be looked at.  Thanks.

**Comment by smithalan92** [comment]
https://github.com/ubershmekel/redditp/pull/114

**Comment by ubershmekel** [comment]
I believe this issue is now resolved with https://github.com/ubershmekel/redditp/pull/114

Thank you for reporting and thank you for the fix @smithalan92
