### ISSUE TITLE
Support Github Pages?

### ISSUE THREAD

**Issue by d33tah** [ubershmekel/redditp#117]
Hi again!

I was playing with redditp and managed to run it without any extra server, after copying index.html to 404.html. Github Pages would then serve this index.html even if I gave it a weird URL and your script worked. Perhaps it would make sense to support this use case?

**Comment by ubershmekel** [comment]
I'm not sure if that would work because some of the assets would be in the wrong directory. Did you test this idea out?

**Comment by d33tah** [comment]
@ubershmekel I tested it and it worked, but only if I assigned a domain so that the resources would sit in the root diretory.

**Comment by d33tah** [comment]
@ubershmekel you can try it out here: https://redditp.d33.pl/

**Comment by ubershmekel** [comment]
Cool. Perhaps we can add this as a note to the README file? I wouldn't want to actively copy between the two all the time.

**Comment by d33tah** [comment]
@ubershmekel copy between what exactly? The redditp.d33.pl fork might go down pretty quickly, it was just an experiment. I'm OK with you posting about it in README.md. I guess I mostly just wanted to let you know that you can use Github Pages to host this project.

**Comment by ubershmekel** [comment]
I added a note to the readme file at https://github.com/ubershmekel/redditp/commit/9a1ce4823bbc307440148c4001f918d79f043569#diff-04c6e90faac2675aa89e2176d2eec7d8

Feel free to reopen if needed.
