### ISSUE TITLE
Failed to handle URL

### ISSUE THREAD

**Issue by xpc101** [ubershmekel/redditp#124]
https://www.redditp.com/r/girlsfinishingthejob returns the message "failed to handle URL" more often than not.  Says to notify ubershmekle.

**Comment by ubershmekel** [comment]
Thanks for reporting. I hope to get to this in 1-2 days. Shouldn't be too hard to fix.

**Comment by ubershmekel** [comment]
Should be fixed now. Redgifs changed their api. I suspect this issue will surface soon with gfycat too. Please re-open if it doesn't work for you after you clear cache (e.g. by opening dev tools in chrome).
