### ISSUE TITLE
Failed To Handle Redgifs URL

### ISSUE THREAD

**Issue by NutGuy8** [ubershmekel/redditp#129]
title says it all

**Comment by ubershmekel** [comment]
Is this still happening?

**Comment by enbyUnicorn** [comment]
It didn't occur to me 'til 2 weeks ago, but now it's an issue with me as well. Tried both Chrome and Firefox...

I'll add some links, but they are obviously NSFW (Porn):

[https://www.redditp.com/r/RealGirls/comments/jfwycm/i_spent_way_too_much_time_on_this/](url)
[https://www.redditp.com/r/RealGirls/comments/i0kmfd/quarantine_has_forced_me_to_get_creative/](url)
[https://www.redditp.com/r/holdthemoan/comments/tf6fmw/ill_be_your_nurse_tonight_gif/](url)
[https://www.redditp.com/r/BustyPetite/comments/tf3b70/my_boobs_look_much_better_when_wet_oiled_or_glazed/](url)
[https://www.redditp.com/r/AnalGW/comments/tf7nu8/hubbys_friend_fucking_my_ass/](url)

**Comment by Foxandxss** [comment]
I second this. It is still happening and it is a pain since many many subreddits is mainly based on redgifs and it is watching blank screens all the time.

**Comment by Foxandxss** [comment]
Yeah, I am sure of that. I read redditp source long ago to replicate the idea for a telegram bot and you pretty much need to update it everytime something changes.

**Comment by enbyUnicorn** [comment]
is fixed now
