### ISSUE TITLE
Redditp website ui broken

### ISSUE THREAD

**Issue by Raijku** [ubershmekel/redditp#132]
Steps to reproduce:
- Open redditp.com/r/portugal (sub-reddit is whatever you prefer)
- Check page ui

Actual result:
Page ui is broken - https://imgur.com/Z9SGRJq

Expected result:
Good old black ui where picture fits the screen to see some good ol por

**Comment by l-one1** [comment]
Can confirm I am also experiencing the issue in the same manner as captured in screenshot.

Additional users are also chiming in that they are experiencing the same in https://old.reddit.com/r/redditp/comments/pxxdab/site_dead_for_anyone_else/ and in the r/redditp subreddit in general.

**Comment by ubershmekel** [comment]
Thank you for chiming in. Is this problem happening at the https://www.redditp.com/ URL too?

**Comment by ubershmekel** [comment]
Also, can you check https://old.redditp.com/ too?

**Comment by Raijku** [comment]
Old one is fine. Normal one is broken

**Comment by l-one1** [comment]
Can confirm when I use old.redditp.com it works correctly.

**Comment by ubershmekel** [comment]
Well, that's trippy. I'll open a ticket with netlify (the host) support then.

**Comment by ubershmekel** [comment]
Wait a sec, I just noticed it says "portugal:15" in the screenshot. Are you folks all from Portugal?

**Comment by Raijku** [comment]
Photo is mine and I'm from Portugal, this was a # represent yo 👌, to the Portuguese sub 😂

**Comment by ubershmekel** [comment]
I just pushed out a workaround. Can you retest?

FYI I also get the ERR_TOO_MANY_REDIRECTS error when I directly browse to https://www.redditp.com/css/style.css

So I've made the code point to https://old.redditp.com/css/style.css

You might need to [hard refresh](https://www.google.com/search?q=browser+hard+refresh)

**Comment by Raijku** [comment]
Aye seems to be working 👌 good job my man 👏

**Comment by l-one1** [comment]
Original site (not old.redditp) is now working for me as well.  Thank you ubershmekel.

**Comment by ubershmekel** [comment]
Thank you for checking. Does anyone still see an error when browsing to https://www.redditp.com/css/style.css ?

**Comment by Raijku** [comment]
https://www.redditp.com/css/style.css

Is working for me 👍

**Comment by ubershmekel** [comment]
Thank you for the report @jerrywilborn I can't currently reproduce that redirect. If you can, let's open a separate new issue and could you also add information about which country and ISP you're using?
