### ISSUE TITLE
Redgifs not automatically playing sound

### ISSUE THREAD

**Issue by JensAltst** [ubershmekel/redditp#148]
I browse subreddits that mostly use redgifs for sharing, and I can't seem to automatically play the sound of redgifs.

Is there a workaround or something?

**Comment by botolo** [comment]
I second this request.

**Comment by ubershmekel** [comment]
If you can figure out a way to open their iframe unmuted - then I can implement it. For example - find a way to make the following link start unmuted:

https://gfycat.com/ifr/grotesquebrilliantbengaltiger

You can reach out to redgifs or gfycat. Asking them how to do that. For now, it seems there isn't a real way to start unmuted with those sites.

**Comment by JensAltst** [comment]
Apparently as far as I could manage to find out via redgifs discord, you should be using their API? But the support couldn't really help me otherwise.
