### ISSUE TITLE
Audio not working on some v.redd.it videos

### ISSUE THREAD

**Issue by rahulanonymous** [ubershmekel/redditp#158]
Link 1- https://redditp.com/r/FingMemes/comments/15efexn/op_is_lazy_to_give_context/
Audio does not work. Video is hosted on Reddit.

Link 2- https://redditp.com/r/Audiomemes/comments/15aas6y/khgd/
Audio works. Video is hosted on Reddit.

Not sure what's causing the issue...

**Comment by ubershmekel** [comment]
Fixed by https://github.com/ubershmekel/redditp/commit/28b9cfcca55ca9c816f4b6ac4f71fc2955c2cac4
