### ISSUE TITLE
No sounds on gifs

### ISSUE THREAD

**Issue by amalgamemnon** [ubershmekel/redditp#162]
Even after enabling sound in both the settings page and the controls panel on the bottom of the screen...

I've confirmed both on the reddit website and on redditp that these videos have sound, but sound is not playing through redditpx

**Comment by ubershmekel** [comment]
I did some work recently to fix audio on redditp. If you're reporting a redditpx issue then it should go to https://github.com/jeffjose/redditpx/issues
