### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by brianseaders** [ubershmekel/redditp#17]
if there was a way that you could make images mass downloadable it would negate the need for an offline mode but i assume this would require a lot more server power because the images would probably half to be zipped. if i could chose a range like 1-100 and hit a download button it would probably be the greatest thing ever.

**Comment by ubershmekel** [comment]
I think an offline mode is out of the scope of this project. If you want to mass download pictures from a subreddit I'd recommend getting a mass downloader and using it on a subreddit page. E.g. https://addons.mozilla.org/en-US/firefox/addon/downthemall/
