### ISSUE TITLE
Redditp seems to be entirely broken for me

### ISSUE THREAD

**Issue by kfoznot** [ubershmekel/redditp#170]
I just get this error and nothing shows up, regardless of which reddit:
![Screenshot 2024-02-12 142315](https://github.com/ubershmekel/redditp/assets/2703830/65c8d651-b271-4b3d-ae86-89af63b0f5b6)

**Comment by omegasome** [comment]
Is it still broken?

If so, which browser are you using, are you using it in regular or private mode, and can you provide an example of a URL on which it is broken?

And does the problem persist when you switch from regular to private browsing (or vice versa)?

**Comment by kfoznot** [comment]
It works now, thanks!

I'm using Chrome in regular mode, and it wasn't working even just with
redditp.com. But it's all good now :)

**Comment by groork** [comment]
Same happening here: Firefox and chrome
![image](https://github.com/ubershmekel/redditp/assets/160770677/1c09112d-c2f9-44e6-a464-b56644509447)

**Comment by omegasome** [comment]
@groork  It does not appear that [r/Homebrewing](https://www.reddit.com/r/Homebrewing/) is an image sub. Do you still get an error if you visit [r/pics](https://www.redditp.com/r/pics/)?

**Comment by omegasome** [comment]
Recommend closing this issue

**Comment by blodt** [comment]
This issue is back in the latest Firefox

I've confirmed Enhanced Tracking Protection is off (have toggled it, etc)

Is there perhaps another setting beyond ETP to look into?

**Comment by ubershmekel** [comment]
@blodt I'm guessing this is a completely different issue. Can you open a new issue with a screenshot of what's going on in your js console?
