### ISSUE TITLE
Please fix (or improve the handling of) the "Redditp booboo TypeError" bug

### ISSUE THREAD

**Issue by ikki4** [ubershmekel/redditp#173]
![image](https://github.com/ubershmekel/redditp/assets/38467650/9102f9a4-adae-4f28-bae6-d3be51e7f8e3)

Pretty much everytime I use redditp, I get this bug. Whenever it occurs, the website stops working and I have to reload the tab to get any response. Isn't it possible to make it so I can just skip the media/post that could not load correctly, so I can keep browsing without having to reload the tab?

**edit:** both times it happened to me today, the posts that redditp could not load were cross-posts ([example](https://www.reddit.com/r/MadeMeSmile/comments/1cs4nby/sikh_dude_passes_the_vibe_check_in_miami/)). Maybe this information can be useful, should anyone decide to look into this issue.

**Comment by ikki4** [comment]
I see that things are being updated. The booboo popup no longer shows, but redditp still freezes whenever it's supposed to show media from a cross-post. It would be good if it didn't freeze, regardless if the problematic media gets shown or not.

**Comment by ubershmekel** [comment]
I thought the recent deploy would fix this but it seems it didn't

https://redditp.com/r/comics/comments/1c4o8kc/hey_what_would_the_earth_3_variants_of_these/

I'll have to take another look

**Comment by ikki4** [comment]
Oh, my bad. I didn't specify that I've been mostly having problems with crosspost videos. Testing it today, I noticed that redditp showed the first image of a crosspost image gallery and didn't freeze, so the recent deploy works. But it still freezes with crosspost videos.

Example: https://redditp.com/r/MadeMeSmile/comments/1dovs4p/long_live_the_dancing_man/

This video is currently post number 12 on https://redditp.com/r/MadeMeSmile/ and when you try to change from post 11 to post 12, it loads the post title and urls, but the media shown doesn't update and the site freezes.

**Comment by ikki4** [comment]
Crosspost videos are no longer making the page crash, it just shows a black screen instead and I can skip to the next post without having to reload the page. 

Thanks to whoever implemented this fix.
