### ISSUE TITLE
Show source subreddit

### ISSUE THREAD

**Issue by mdroidian** [ubershmekel/redditp#18]
This probably isn't a popular request, but I wouldn't mind be able show/toggle the source subreddit if the using multiple subreddits, ie;

redditp/r/funny+gifs+pics

show souce when from /r/funny

**Comment by utopiabound** [comment]
I just pushed a patch to fix iOS mobile. https://github.com/utopiabound/redditp/commit/db75e5ad6ed2af941c972475ed9dadaef9ee99a4

**Comment by ubershmekel** [comment]
Please be mindful of tabs vs spaces and indentation in general next time please. Merged.

**Comment by ubershmekel** [comment]
One more minor note - the fullscreen checkbox wasn't updating when you hit F11 on chrome. Chrome thinks it's a security issue http://stackoverflow.com/questions/21103478/fullscreenchange-event-not-firing-in-chrome it seems. So I made the fullscreen be toggled by a button.
