### ISSUE TITLE
Redditp Architecture.

### ISSUE THREAD

**Issue by 0xE282B0** [ubershmekel/redditp#27]
Hey,
I've added some features to my fork of redditp like Imgur albums http://smielke.github.io/redditp/#/imgur/a/l68R9 or gfycat support http://smielke.github.io/redditp/#/domain/gfycat.com but it is not well written and I sometimes get confused with the architecture of the code.

What do you think about a new redditp version where you can register plugins which handle the media URLs?

**Comment by JoshWillik** [comment]
**Disclaimer:** Not the author

This is a good idea. I'm going to play around with this and see if I can make it work.

**Comment by JoshWillik** [comment]
Update: This is working on my fork
