### ISSUE TITLE
Any way to bypass "Failed Ajax" error, and keep the slideshow presentation going without user input? Also, Ajax errors seem to appear more frequently in Chrome than in Firefox

### ISSUE THREAD

**Issue by JeffKang** [ubershmekel/redditp#28]
http://www.reddit.com/r/redditp/comments/2vmv7b/any_way_to_bypass_failed_ajax_error_and_keep_the/

Any way to bypass "Failed Ajax" error, and keep the slideshow presentation going without user input? Also, Ajax errors seem to appear more frequently in Chrome than in Firefox

**Resume after "Failed Ajax" error**

First off, this program is amazing, and has it has kept my old, Asian grandmother entertained for lots of time.
 
Thank you so much for creating it.

I opened the console with F12, which was suggested in a previous query about the "Failed Ajax" error.
 
There are several entries of "failed", with a link on the right.

I think that these were for previous images that appeared black, but the presentation continued on.

After a "Failed Ajax" comes up, it says "Uncaught TypeError: undefined is not a function".
 
What's on the right varies.
 
(It's a JSON file instead of a link?).

---

Here is the error on 3 separate occasions:

http://www.reddit.com/user/bboyjkang/m/citpo.json?jsonp=jQuery19109659527405165136_1423658241019&after=t3_2vhl6i&&_=1423658241022

http://www.reddit.com/user/bboyjkang/m/citpo.json?jsonp=jQuery191018773288885131478_1423706531735&after=t3_2vkyfn&&_=1423706531738

I think that there was one time where I couldn't copy the text on the right, but I could open it like the other 2 error instances, so I copied what was inside.

Here's part of it.

/**/jQuery1910120294198859483_1423693532073({"kind": "Listing", "data": {"modhash": "", "children": [{"kind": "t3", "data": {"domain": "farm8.staticflickr.com", "banned_by": null, "media_embed": {}, "subreddit": "CityPorn", "selftext_html": null, "selftext": "", "likes": null, "user_reports": [],
 
This is the multi Reddit that was made for my grandma, and was used to produce those errors.

http://redditp.com/user/bboyjkang/m/citpo

---

I don't mind these Failed Ajax errors, but I wish there was a way that the slideshow would recover from the stop, and resume without user input.

I tell my grandma to press the OK, and then the arrow keys to try to keep it going.

It doesn't work most of the time, so we have to start at the beginning again.

If it can eventually resolve itself without intervention, even if it has to skip several pictures, or takes a while, that would be helpful (has some mild arthritis).

---

**"Failed Ajax" error occurs more frequently in Chrome?**

A "Failed Ajax" error seems to occur more frequently in Chrome as opposed to Firefox.
 
This is the same case for both my computer, and my grandma's computer, where the errors will also mainly occur in Chrome.

---

For my computer:

I’m currently using Firefox, and that has all my extensions and stuff.

My Chrome only has a couple extensions, and disabling them didn’t affect the problem.

What little there is left is synced to my Google account, so I was easily able to test and recover from a fresh reinstallation.

Reinstalling Chrome (Revouninstaller, CCleaner, Voidtools Everything Search desktop search program for traces) didn’t help.

For my grandma’s computer:

My grandma’s Chrome browser almost nothing on it, and also disabling what was there did not change anything.

Her computer never had Firefox before, but I installed it recently, and tried the slideshow presentation there for a bit.

I don’t think there was an Ajax error, and if there was, it didn’t appear as fast as in Chrome.

---

The downside for me with Firefox is that it will crash when you leave the slideshow on long enough.

I think that it takes longer for that to happen in Chrome, and that’s when you get that purple screen with the, “Either Chrome ran out of memory or the process for the webpage was terminated for some other reason.”.

I don’t use the program often, and when I do, it's not for a long amount of time, so I don’t really notice these failed Ajax errors.

My grandma doesn’t complain when there’s an issue, so I don’t know the extent of these errors, and if it has always been this way.

Thanks.

**Comment by ubershmekel** [comment]
Thank you for the detailed report. I'll look into this in the next week or two.

**Comment by JeffKang** [comment]
Feel free to drop a comment in my Reddit thread so that I can gild it (cheaper since I already have credits)

Regardless of whether the issue can be fixed, the program has already been so beneficial.

**Comment by JeffKang** [comment]
Feel free to drop a comment in my Reddit thread so that I can gild it
(cheaper since I already have credits)
Regardless of whether the issue can be fixed, the program has already been
so beneficial.

**Comment by ubershmekel** [comment]
I added a "toast" feature yesterday. I can use that instead of a blocking alert upon error I can make it be a small toast on the top right. That way you know it broke but the presentation will chug along. I'll see what I can do the next few days.

**Comment by JeffKang** [comment]
Cool. Thanks for the work.

**Comment by ubershmekel** [comment]
It's live e.g. check out
https://redditp.com/r/gifsdklafjlskdf

Let me know if that works for you.

**Comment by JeffKang** [comment]
I see the red notification that momentarily disappears.

**Comment by ubershmekel** [comment]
Cool. If the presentation keeps going without further user input then I guess I'll call this fixed in https://github.com/ubershmekel/redditp/commit/f08897b7e0cdd822ff496a8e19d911752c112740

Please reopen if you feel otherwise.

**Comment by JeffKang** [comment]
I'm testing a 3 subreddit slideshow for my grandma.
I see it going up to picture 1500+.
I don't remember seeing it go that high without stopping for her computer.
Looks good so far. Thanks.
