### ISSUE TITLE
The links should open in a new tab

### ISSUE THREAD

**Issue by nkmathew** [ubershmekel/redditp#29]
Especially the **comments** and **image** links. Saves us from that extra key-press

**Comment by ubershmekel** [comment]
This is a personal preference issue. There's no right or wrong. Personally I prefer leaving the default link behavior and using middle-click or ctrl-click to open a link in a new tab. That's what reddit does too.

**Comment by nkmathew** [comment]
Reddit has the **[l+c]** and **[l=c]** links though. Is supporting this out of question for you maybe through some setting?

**Comment by ubershmekel** [comment]
I have never in my life seen those. Thanks for pointing them out. I don't mind a `[l+c]` button.

**Comment by jluce50** [comment]
The problem with the default behavior is that when it opens in the same tab, you lose your place in the slideshow and have to start over. This can be incredibly frustrating.

**Comment by Hrxn** [comment]
Love this site, really great, but here is something that I would change:

Instead of (or maybe in addition to) the 'i' and 'c' keys for opening item or comments in a new tab, open them in a new *background* tab.

This is especially useful when you use a rather low delay for auto-advance. Just watch the slideshow at a higher pace, and when you think you like an image, just press one key, and then watch your selection later.

**Comment by Hrxn** [comment]
BTW, manually clicking on 'comments' or 'image' opens the link in the same tab. Ctrl+Click opens in a background tab, as expected.

**Comment by rogerbinns** [comment]
When using a mobile device/tablet the default behaviour is extremely annoying as it is considerably more difficult to open in a new tab.  It basically involves doing this:

* Expanding the panel
* Long holding "image" assuming you hit the right part of the screen
* Going to choose "Open in new tab" when the menu appears, but auto-advance means it is a different image now
* Touching to dismiss menu
* Turning off auto-next
* Going back to the image you wanted
* Long holding image
* Choose open in new tab
* Turn auto-next back on

Also if you missed "Open in new tab" and hit "Open", then when you hit back the slideshow starts from the beginning and you have to work your way through back to where you are.

A suggestion for better UI:
* Have somewhere to click/touch that puts up an overlay on the screen
* While the overlay is up auto-next is paused
* Overlay has big buttons (ie easy to hit with fingers) with most likely 5 actions including open in new tab
* Overlay auto-dismisses after 5 seconds of not using it
* Auto-next resumes when overlay goes away

That would turn it into two clicks and have far less scope for errors

**Comment by ubershmekel** [comment]
Redditp could extremely improve the mobile experience. I do agree.

**Comment by hppavilion1** [comment]
@Hrxn Perhaps bind those to 'I' and 'C' (shift+i and shift+c)? Doesn't break existing use, easy to type, semi-intuitive, doesn't bloat the UI, allows you to use whichever is best for the situation at hand...

**Comment by ubershmekel** [comment]
I thought I might as well change the links to open in new tabs as that's the default on reddit now too. Probably need a better name for that `image` button too.
