### ISSUE TITLE
[suggestion] handling of all images loaded 

### ISSUE THREAD

**Issue by MrHant** [ubershmekel/redditp#35]
After all the images are loaded - dash is added to "numberButtons" and images are loaded again.
For example we have 3 photos, buttons will look following way:
[1] [2] [3] [-] [4] [5] [6] [-]

Why is it working this way?
Won't it be more intuitive to start displaying from 1st image again?

**Comment by ubershmekel** [comment]
Can you give me a link where you experience this? Which browser are you seeing this in? I don't see this behavior.

**Comment by MrHant** [comment]
No, sorry. Can't find one at the moment.
It was a pretty small subreddit with about 6 images (one page).
We can close this one until any further occasions.
