### ISSUE TITLE
Rebuild and potential redditp2?

### ISSUE THREAD

**Issue by JoshWillik** [ubershmekel/redditp#44]
Hi there @ubershmekel. I have a proposal for you.
I thought this was a cool project with a bunch of potential.
### The Rebuild

When I was looking through the issues and future features, I saw that many were going to be difficult to add without a code cleanup and/or rebuild.

So I'm currently working towards a rebuild over at [JoshWillik/redditp](https://github.com/JoshWillik/redditp).
You can see a (temporary) live demo of this system running [here](https://redditp2.joshwillik.com)

_(Although the UI looks very different than the current redditp, that's not a necessary part of the system and it could be made to look like the current redditp with minimal to moderate effort.)_

This rebuild is about 75% of the way towards feature parity with the existing redditp from a UI perspective. 
From a media standpoint, I hope to have Gyfcat videos, imgur albums, imgur pages, and youtube videos by the time I'm done.

The rebuild features a plugin based architecture (as requested in #27). This should allow redditp to better handle a variety of media types.
### The Proposal

I don't have time to run a redditp clone, so if you're willing, I'd love for you to adopt this rebuild when it's finished. I'd be more than willing to stick around and help if you need any pointers on the build system or the new features of Javascript. I might even add a feature or two, but I don't have time to be a lead mantainer.

Is this something you would be interested in?

**Comment by JoshWillik** [comment]
Just to keep you updated, [the demo](https://redditp2.joshwillik.com) now has support for image posts, imgur posts, and gfycat posts.

**Comment by JoshWillik** [comment]
@ubershmekel Another update.
I'm pretty much at feature parity with the official redditp now.

My rebuild will close #34, #33, #31, #27, and #6. 

I really think this project should be actively mantained. If you can't do that, let me know and we can talk.

**Comment by ubershmekel** [comment]
Thank you for making this. But I have to say commits like this https://github.com/JoshWillik/redditp/commit/14959ff10a32efa095689289583f81d4b9d61233

> IE support does not matter to me

Make me uncomfortable just merging everything in.

This is a side project of mine but I still would like to apologize it takes me a long time to respond here. I would love for us to collaborate.

https://github.com/ubershmekel/redditp/pull/41

That PR looks reasonable but it has enough changes that I'd like to review it before merging. I hope that's ok with you.

**Comment by JoshWillik** [comment]
@ubershmekel My rebuild already supports waiting for gfycats out of the box. If you choose to adopt my changes, #41 will not be needed.

It's a complete rewrite, so I understand that merging mine would change ~~a lot~~ all of the code. But it includes a much more flexible architecture and a clearer logic flow.

The comment about IE  was more of a joke than a serious statement. I do think IE support is important for a public facing project, but at the time I was more focused on making the core product work, so the IE support code was just getting in my way.

I think for the sake of developer sanity and to help old IEs die off, we should cap backwards compatibily to IE 10. 
IE 8 and 9 have ~1% market share each. IE 9 was last shipped with Vista, which has been out of date for quite a number of years here. Even 7 is at end of life now, and that has IE11.

Besides this, the target market is not old grandmas. Our users are reddit users. They're pretty smart and at least decently tech savvy. I suspect they know to use a decent browser.
If you want confirmation of this, add Google analytics to redditp and check out the breakdown of browsers.

If limiting support to IE 10 and forwards is acceptable to you, then the `Array.indexOf` hack will not be needed, as IE added support for this in version 9.

The `console.log` hack will also be un-needed for 2 reasons.
* We should not ship code with `console.log`s left in it
* IE supports `console.log` as of version 10

I would really like it if you took a look at my code and let me know how you felt about the codebase so far. I look forward to hearing back from you.

**Comment by ubershmekel** [comment]
Last month redditp saw the following IE traffic:

Version | Sessions
----------- | -----------
11 | 5003
10 | 697
9 | 148
8 | 52
7 | 25
6 | 2

I don't plan to test IE actively but intentionally breaking IE support doesn't help my personal developer sanity.

When I did the `console.log` hack it was for debugging on old versions of IE. I don't do that too often so I wouldn't miss that as sorely as `indexOf`.

I'll try and review the PR in the next month.

**Comment by maximousblk** [comment]
I am very new to programming but i am a good designer. i have made a redesign for redditp and would like if it is considered. Like @JoshWillik i saw this as a good project and would love it if it looks good.

[This](https://www.figma.com/file/DDPt6A702bipRNEHCR5nye/redditp) is what I would like to make if i knew better programming.

also please @ubershmekel add a getting started guide for new developers if you want this to go well. if only I knew better about the structure and the environment setup of this project, the pull request would have been ready by now. i will still do it if you made it clear how to start developing this project.

Please consider this cuz i really like this project.

**Comment by ubershmekel** [comment]
@maximousblk there are some great ideas in your design. Do you think the scrolling should remain horizontal or change to vertical?

**Comment by maximousblk** [comment]
@ubershmekel on phone it should change to vertical. i can make a phone redesign too if you need it and want to implement it. should i make the vertical design?

**Comment by maximousblk** [comment]
I made some changes to [the designs](https://www.figma.com/file/DDPt6A702bipRNEHCR5nye/redditp?node-id=0%3A1) like making a mobile device design and added mockups just in case.

**Comment by JoshWillik** [comment]
@ubershmekel This PR has been open for a while, and in retrospect I can see that a ground-up rebuild isn't likely to be welcome.

I'm going to close this to reduce your cognitive load for this project. Feel free to re-open it if you think it would be valuable.

@maximousblk - your UI updates seem valuable, I recommend that you open a new issue for them
