### ISSUE TITLE
Mild observation: slideshows of just a single subreddit seem to have less black screens then multireddits with multiple subreddits

### ISSUE THREAD

**Issue by JeffKang** [ubershmekel/redditp#46]
Maybe it’s just me, but I seem to notice that slideshows of just a single subreddit seem to have less black screens then multireddits with multiple subreddits.

I’m getting little to no black screens with a slideshow of /r/pics.

As soon as I add just two more subreddits like /r/funny and /r/gifs, black screens show up.

Even previously fine /r/pics pictures go black in a 3 subreddit multireddit.

**Comment by ubershmekel** [comment]
I just pushed out a change with better gfycat support. Please comment with a link if you notice more issues.

**Comment by JeffKang** [comment]
Thanks.

**Comment by JeffKang** [comment]
So far, I'm not seeing any black screens for a multireddit slideshow with as much as 10 subreddits.

**Comment by ubershmekel** [comment]
Cool. Thanks for the report. Please reopen if you see it again.

**Comment by JeffKang** [comment]
The slideshow is fine for most of the time, but here is an example instance where It pauses on black.

http://i.imgur.com/TDMCsV6.gifv
https://www.reddit.com/r/oddlysatisfying/comments/47dr53/dam/

Edit: I just clicked on the image link, and I think the removal of the image is the cause:
“The image that you are requesting does not exist”
http://i.imgur.com/removed.png
