### ISSUE TITLE
Preloading and progress in slideshow issues

### ISSUE THREAD

**Issue by Hrxn** [ubershmekel/redditp#48]
I think it's related to
this: https://www.reddit.com/r/redditp/comments/462wtg/redditp_does_not_preload_the_entire_slideshow/

But I guess this has something to do with the NSFW switch and the NSFW subreddits.
Because, for example, r/pics seems to work, while r/gonewild does not.

That's what I am currently observing.
Latest Chrome Stable x64 on Windows.

**Comment by ubershmekel** [comment]
What are you observing exactly?

**Comment by Hrxn** [comment]
Exactly the same as described in the linked comments, e.g. I see 10-25 images, give or take, and can't progress beyond that.

But only on NSFW subreddits (red numbers), other subreddits seem to work.

**Comment by ubershmekel** [comment]
I deployed a fix for not loading past the first original set of images about 6 hours ago. Can you see if it fixed that for you as well?

**Comment by Hrxn** [comment]
Good news:

Clicking on the last item in the initially loaded set now loads some new images, maybe 15-25 a batch or something in the range of that.

Thanks for fixing this, excellent job! :+1: 

Now I only need a hotkey to open the 'image' or 'comment' link in a new background tab, and that site is pretty much perfect :wink:

**Comment by ubershmekel** [comment]
Cool. Thank you for reporting this.
