### ISSUE TITLE
Error while loading any gif

### ISSUE THREAD

**Issue by mathiasHillmann** [ubershmekel/redditp#54]
![080c1a8270a5e000bdc95bfc0f52d23f](https://cloud.githubusercontent.com/assets/9846320/17479931/c92c5394-5d4b-11e6-88c2-e05befc8032a.png)

**Comment by ubershmekel** [comment]
Which browser and OS are you using? Do you have an example subreddit?

**Comment by mathiasHillmann** [comment]
OS: Microsoft Windows 10 Pro 64 bit
Browser: Mozilla Firefox 47.0.1
Example: http://redditp.com/r/gifs

**Comment by Hrxn** [comment]
Extensions? Tried a clean profile?

**Comment by mathiasHillmann** [comment]
Sorry for the late reply.

Specs (Not sure if relevant, but might as well):
Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release.160802-1857)
Processor: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 CPUs), ~3.6GHz
Memory: 4096MB RAM
GPU: NVIDIA GeForce 9400 GT 

Browser: Mozilla Firefox 48.0
Add-ons: BetterTTV, Reddit Enhancement Suite, uBlock Origin
Result: Error.

Browser: Mozilla Firefox 48.0
Add-ons: Clean profile.
Result: Error.

Browser: Google Chrome 52.0.2743.116 m
Add-ons: Google Suite (Docs, Sheets + Slides), BetterTTV, uBlock Origin, TamperMonkey.
Result: Working normally, no error presented.

Browser: Google Chrome 52.0.2743.116 m
Add-ons: Clean profile.
Result: Working normally, no error presented.

Browser: Opera 39.0.2256.48
Add-ons: Clean profile.
Result: Working normally, no error presented.

**Comment by ubershmekel** [comment]
My firefox 46 also shows `Redditp booboo: TypeError: vid_jq[0].play(...) is undefined`

I'm surprised firefox does not return the same promise from the `play()` call. Anyhow, should be fixed now if you Ctrl-F5 to hard refresh.

Thank you for reporting this! Feel free to reopen if it isn't fixed.
