### ISSUE TITLE
Getting a 404 on every subreddit

### ISSUE THREAD

**Issue by TheEisbaer** [ubershmekel/redditp#60]
Example: https://redditp.com/r/pics

Not Found

The requested URL /r/pics was not found on this server.

**Comment by ubershmekel** [comment]
Thank you for filing this issue, I migrated the app to a different machine and did not notice the `.htaccess` files weren't working. I've now set the dns to the old machine until I figure out the problem.

Please flush your dns and tell me if it's working now.

**Comment by ubershmekel** [comment]
I've fixed it on the new server as well by modifying the httpd.conf. Please let me know if this is still an issue. I apologize for the disruption. Many thanks @TheEisbaer !

**Comment by TheEisbaer** [comment]
Thanks its working now @ubershmekel
