### ISSUE TITLE
Fix GFYCat /detail/ URLs

### ISSUE THREAD

**Issue by akaleeroy** [ubershmekel/redditp#64]
URLs like `https://gfycat.com/gifs/detail/flatgrouchyblackfly` fail to load.

The regex at [EmbedIt.js#L86-L90](https://github.com/ubershmekel/redditp/blob/master/js/EmbedIt.js#L86-L90) doesn't seem to accommodate this type of URL. Found this one that matches well: `/(?:http:|https:|)(?:\/\/|)(?:gfycat\.com\/(?:\w*\/)*)(\w+$)/gi`

**Comment by hppavilion1** [comment]
Created a pull request to do just this: [github.com/ubershmekel/redditp/pull/65](https://github.com/ubershmekel/redditp/pull/65) (I use my own regex solution though- just adding the option for `gifs/detail/` to appear.)

**Comment by hppavilion1** [comment]
Oh, that pull has been accepted and closed the issue... I can't close it myself; @ubershmekel ?

**Comment by ubershmekel** [comment]
Thanks again @hppavilion1
