### ISSUE TITLE
Is there a max length of url for multireddits?

### ISSUE THREAD

**Issue by saspelund** [ubershmekel/redditp#70]
I am now subscribed to 242 picture subreddits (lots of /r/random) and the multireddit url is 2907 characters long which is causing the powerpoint to not load. redditp was working up until recently (as in before I added a few more subreddits) so I must have hit a limit. I was wondering if there is a hard coded limit that can be increased or if I just need to stay under it. I could simply unsubscribe to some of the less active/not as good subreddits to stay under whatever limit there is, but I'd like to know what it is.

Cheers!

**Comment by ubershmekel** [comment]
Can you give me an example working url and an example not working url?

**Comment by ubershmekel** [comment]
Closed it for lack of a response for over a year. Please re-open or let me know if there is still an issue.
