### ISSUE TITLE
support old.reddit.com

### ISSUE THREAD

**Issue by 2vek** [ubershmekel/redditp#74]
on `www.reddit.com` I can just add a single `p` after reddit and get redirected to `redditp.com`.
but, with `old.reddit.com` I have to add a `p` and then remove `old.` to go to `redditp.com`
one is convenient, other is hassle.

**Comment by ubershmekel** [comment]
Thank you for the report.

https://old.redditp.com/ seems to be working probably since around February when I transitioned to netlify.

I'm closing this issue but please feel free to re-open it or another if it isn't working or if another subdomain is needed.
