### ISSUE TITLE
/new may show /new?rising

### ISSUE THREAD

**Issue by Jwink3101** [ubershmekel/redditp#8]
Example:
http://www.redditp.com/r/pics/new
works, but
http://www.redditp.com/r/bicycling/new
says no displayable images. Note that http://www.redditp.com/r/bicycling **does** work.

Tested in both regular and incognito windows with Chrome Mac 24.0.1312.56 (up to date on 2013-01-23)

**Comment by ubershmekel** [comment]
Seems this fixed itself.

Maybe reddit fixed the bug. http://redditp.com/r/bicycling/new?sort=rising doesn't even work anymore because it's https://www.reddit.com/r/bicycling/rising/ which does work but has fewer images. So I'm closing this off.
