### ISSUE TITLE
Sound enable/disable preference

### ISSUE THREAD

**Issue by smarek** [ubershmekel/redditp#83]
Hi, the same way we currently have nsfw preference, could there be an sound preference?

Simple way is to reflect the preference in `muted` attribute presence
Advanced would be to also transfer the volume level from one video tag to another (javascript accessible property `videotag.volume` with values from 0.0 to 1.0 meaning 0% to 100% volume)

If you agree with proposal, i'd be willing to create PR for your review

**Comment by ubershmekel** [comment]
Sounds like a good idea. A PR would be welcome.

**Comment by smarek** [comment]
Closing as the PR exists #84

**Comment by ubershmekel** [comment]
Good question @murgo I'll try to get to it ASAP. I realize it's been a long time coming. @jeffjose fyi
