### ISSUE TITLE
UI/UX redesign for better experience and mobile support

### ISSUE THREAD

**Issue by maximousblk** [ubershmekel/redditp#97]
As of now, the UI seems janky and and doesn't work great cross-platform.

I have made some UI designs for the project that can be applied to the project without changing the functionality that much. Here is a sneak peek:

![Desktop-preview](https://user-images.githubusercontent.com/28438021/71715877-e6982b80-2e38-11ea-9571-7550ddc7afab.png)

These designs are not final but that's where I would start. The design files can be found [here](https://www.figma.com/file/DDPt6A702bipRNEHCR5nye/redditp?node-id=0%3A1).

I would like to handle the designs but anyone who wants to help is welcome to copy the designs and work on them. I cannot be actively working on the designs as of now because I live at a hostel where I don't have access to PCs at all.

**Comment by maximousblk** [comment]
I just made new logos for the project
![Screenshot (66)](https://user-images.githubusercontent.com/28438021/71722004-56b0ac80-2e4d-11ea-8e9b-49c19823c0a3.png)

Please let me know if I should keep doing this cuz I won't like it if this all goes waste

**Comment by ubershmekel** [comment]
Thank you for this effort @maximousblk 

* What do you believe will be gained from github projects over using just github issues?
* I would suggest not having a mega issue for everything. Those are harder to close and make progress on. E.g. if there's code clean-up required, that should be its own issue.
* I'm not sure about the logo you suggested. I don't understand how it relates to the name, form or function of redditp. Perhaps you should open an issue for discussing the logo?
* With regards to a roadmap - it's a bit difficult to coordinate an open source project. It makes sense to prioritize tasks, but the cadence of progress can be less predictable.

**Comment by maximousblk** [comment]
Sorry for the inconvenience @ubershmekel 

- unlike issues, projects offer a more visual representation of what is being worked on and what is in the backlog with the convenience of assigning the issues and reviews to individual contributors. More about project boards can be found [here](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards)

- I have edited the issue and will create separate issues for other problems.

- The logo is a lowercase r and p but stylised in a minimal way with r in white and p in red color

- managing roadmap is made easy by using a projects board because it helps you prioritise between say, old bug fixes or new features.

clearing that out, i'm currently working on a new about page with the new design.

**Comment by maximousblk** [comment]
it would be better if the question label is changed to enhancement

**Comment by maximousblk** [comment]
New about page, new hotkeys page, redesigned 404 page and redesigned homepage are almost ready.

I couldn't completely redesign the home page as i planned but it is same layout wit a bit of new design.

**Comment by maximousblk** [comment]
New pull request #101 has the new pages and some marked bugs which i was not sure of what to do.

**Comment by maximousblk** [comment]
I cannot work on this this design anymore untill late February. I'm back at my hostel and can only do things on my mobile phone. #101 still needs some work (better mobile layout) but is still in better shape than what is live now. Live preview is linked above so that you can see the difference.

**Comment by ubershmekel** [comment]
Thank you for this cool redesign. Have fun at the hostel. I'll try to review as soon as I can which I hope would be some time in January.

**Comment by maximousblk** [comment]
Thanks for your time
